services:
  - type: web
    name: mtfsa-autoscaler
    env: python
    plan: free
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app_final.py --server.port $PORT --server.address 0.0.0.0
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
